In [1]:
import numpy as np

In [2]:
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])


In [3]:
result_matrix = np.dot(A, B)


In [4]:
print("行列の積の計算結果:")
print(result_matrix)


行列の積の計算結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [5]:
max_value = np.max(result_matrix)
print("\n行列の要素の最大値:")
print(max_value)



行列の要素の最大値:
47
